# Pull a subset from the full dataset (*found in `raw_data_combined.csv`*)<br>for easier testing when parsing `desc` (*description*) values

## <font color=MediumSlateBlue>1) Import Libraries</font>

In [1]:
# Import libraries
import pandas as pd
from pathlib import Path

# ~~~~~~~~~~ VERY IMPORTANT NOTE ~~~~~~~~~~
actually_save_csv = True

## <font color=MediumSlateBlue>2) Import Full Dataset for Slicing</font>

In [2]:
full_df = pd.read_csv(Path('./Resources/raw_data_combined_v2.csv'), index_col='uid')

C:\Users\fsurl\.conda\envs\SQL\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1,5,20,21,22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\fsurl\.conda\envs\SQL\lib\site-packages\numpy\lib\arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

## <font color=LightSalmon>3) Review Full Dataset</font>

### <font color=PaleGreen>3a) Check Column Names</font>

In [4]:
full_df.columns.values

array(['city', 'price', 'year', 'manufacturer', 'make', 'condition',
       'cylinders', 'fuel', 'odometer', 'title_status', 'transmission',
       'VIN', 'drive', 'size', 'type', 'paint_color', 'lat', 'long',
       'posting_date', 'desc', 'region', 'model'], dtype=object)

### <font color=PaleGreen>3b) Check Column Types</font>

In [5]:
full_df.dtypes

city             object
price             int64
year            float64
manufacturer     object
make             object
condition        object
cylinders        object
fuel             object
odometer        float64
title_status     object
transmission     object
VIN              object
drive            object
size             object
type             object
paint_color      object
lat             float64
long            float64
posting_date     object
desc             object
region           object
model            object
dtype: object

## <font color=MediumSlateBlue>4) Slice Subset of Full Dataset</font>

### <font color=PaleGreen>4a) Slice the Full Dataset</font>

In [6]:
subset_df = full_df.iloc[-500:]

### <font color=PaleGreen>4b) Review the New DataFrame</font>

In [8]:
# subset_df
subset_df.dtypes

city             object
price             int64
year            float64
manufacturer     object
make             object
condition        object
cylinders        object
fuel             object
odometer        float64
title_status     object
transmission     object
VIN              object
drive            object
size             object
type             object
paint_color      object
lat             float64
long            float64
posting_date     object
desc             object
region           object
model            object
dtype: object

### ~~<font color=PaleGreen>4c) Drop Extra `uid` Column</font>~~

~~For reasons not understood as of this writing, there is an additional `uid` column present when `raw_data_combined.csv` is first imported: `uid` and `uid.1`~~

~~The desired `uid` column for our indexing purposes is in fact `uid.1` so:~~
~~1. Drop the incorrect `uid` column (`uid`) -- which is *not* the index~~
~~2. Rename the existing index from `uid.1` to  `uid`~~

In [26]:
# # drop the `uid` column which is not the index
# subset_df.drop(columns='uid', inplace=True)
# # rename the existing index from `uid.1` to simply `uid`
# subset_df.index.rename('uid', inplace=True)

C:\Users\fsurl\.conda\envs\SQL\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

### <font color=PaleGreen>4d) Review the DataFrame</font>

In [9]:
subset_df

,city,price,year,manufacturer,make,condition,cylinders,fuel,odometer,title_status,...,drive,size,type,paint_color,lat,long,posting_date,desc,region,model
uid,,,,,,,,,,,,,,,,,,,,,
426380,NaN,7550,2015.0,dodge,NaN,NaN,4 cylinders,gas,73269.0,clean,...,fwd,NaN,sedan,grey,40.745755,-111.939740,2021-04-27T23:45:57-0600,Engine: 4 Cylinders Transmission: Automatic Ti...,wyoming,dart sxt
426381,NaN,13950,2017.0,nissan,NaN,NaN,4 cylinders,gas,28709.0,rebuilt,...,4wd,NaN,SUV,black,40.745787,-111.939869,2021-04-27T22:45:22-0600,Engine: 4 Cylinders Transmission: Automatic Ti...,wyoming,rogue awd
426382,NaN,11500,2012.0,chevrolet,NaN,good,8 cylinders,gas,175102.0,rebuilt,...,4wd,full-size,truck,black,41.888456,-107.495083,2021-04-27T20:54:00-0600,Well taken care of truck for sale.,wyoming,silverado
426383,NaN,8000,2002.0,ford,NaN,like new,8 cylinders,gas,139500.0,clean,...,4wd,full-size,truck,white,41.439000,-105.801000,2021-04-27T20:31:22-0600,Very clean and straight plow truck. All record...,wyoming,f-150
426384,NaN,4950,2012.0,dodge,NaN,NaN,6 cylinders,gas,142761.0,clean,...,fwd,NaN,van,black,40.745820,-111.939998,2021-04-27T20:10:23-0600,Engine: 6 Cylinders Transmission: Automatic Ti...,wyoming,grand caravan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,NaN,23590,2019.0,nissan,NaN,good,6 cylinders,gas,32226.0,clean,...,fwd,NaN,sedan,NaN,33.786500,-84.445400,2021-04-04T03:21:31-0600,Carvana is the safer way to buy a car During t...,wyoming,maxima s sedan 4d
426876,NaN,30590,2020.0,volvo,NaN,good,NaN,gas,12029.0,clean,...,fwd,NaN,sedan,red,33.786500,-84.445400,2021-04-04T03:21:29-0600,Carvana is the safer way to buy a car During t...,wyoming,s60 t5 momentum sedan 4d
426877,NaN,34990,2020.0,cadillac,NaN,good,NaN,diesel,4174.0,clean,...,NaN,NaN,hatchback,white,33.779214,-84.411811,2021-04-04T03:21:17-0600,Carvana is the safer way to buy a car During t...,wyoming,xt4 sport suv 4d
426878,NaN,28990,2018.0,lexus,NaN,good,6 cylinders,gas,30112.0,clean,...,fwd,NaN,sedan,silver,33.786500,-84.445400,2021-04-04T03:21:11-0600,Carvana is the safer way to buy a car During t...,wyoming,es 350 sedan 4d
426879,NaN,30590,2019.0,bmw,NaN,good,NaN,gas,22716.0,clean,...,rwd,NaN,coupe,NaN,33.779214,-84.411811,2021-04-04T03:21:07-0600,Carvana is the safer way to buy a car During t...,wyoming,4 series 430i gran coupe

## <font color=MediumSlateBlue>5) Save Subset DataFrame to a CSV</font>

### <font color=PaleGreen>5a) Save the Subset DataFrame to a CSV</font>

In [10]:
if actually_save_csv:
    subset_df.to_csv(
        Path('./Resources/subset_for_testing.csv'),
        header=subset_df.columns.values,
        index_label='uid'
        )

### <font color=PaleGreen>5b) Read Back the New CSV File for Confirmation</font>

In [11]:
test_subset_df = pd.read_csv(
    Path('./Resources/subset_for_testing.csv'),
    index_col='uid'
)

### <font color=PaleGreen>5c) Review New DataFrame for Confirmation</font>

In [12]:
test_subset_df

,city,price,year,manufacturer,make,condition,cylinders,fuel,odometer,title_status,...,drive,size,type,paint_color,lat,long,posting_date,desc,region,model
uid,,,,,,,,,,,,,,,,,,,,,
426380,NaN,7550,2015.0,dodge,NaN,NaN,4 cylinders,gas,73269.0,clean,...,fwd,NaN,sedan,grey,40.745755,-111.939740,2021-04-27T23:45:57-0600,Engine: 4 Cylinders Transmission: Automatic Ti...,wyoming,dart sxt
426381,NaN,13950,2017.0,nissan,NaN,NaN,4 cylinders,gas,28709.0,rebuilt,...,4wd,NaN,SUV,black,40.745787,-111.939869,2021-04-27T22:45:22-0600,Engine: 4 Cylinders Transmission: Automatic Ti...,wyoming,rogue awd
426382,NaN,11500,2012.0,chevrolet,NaN,good,8 cylinders,gas,175102.0,rebuilt,...,4wd,full-size,truck,black,41.888456,-107.495083,2021-04-27T20:54:00-0600,Well taken care of truck for sale.,wyoming,silverado
426383,NaN,8000,2002.0,ford,NaN,like new,8 cylinders,gas,139500.0,clean,...,4wd,full-size,truck,white,41.439000,-105.801000,2021-04-27T20:31:22-0600,Very clean and straight plow truck. All record...,wyoming,f-150
426384,NaN,4950,2012.0,dodge,NaN,NaN,6 cylinders,gas,142761.0,clean,...,fwd,NaN,van,black,40.745820,-111.939998,2021-04-27T20:10:23-0600,Engine: 6 Cylinders Transmission: Automatic Ti...,wyoming,grand caravan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,NaN,23590,2019.0,nissan,NaN,good,6 cylinders,gas,32226.0,clean,...,fwd,NaN,sedan,NaN,33.786500,-84.445400,2021-04-04T03:21:31-0600,Carvana is the safer way to buy a car During t...,wyoming,maxima s sedan 4d
426876,NaN,30590,2020.0,volvo,NaN,good,NaN,gas,12029.0,clean,...,fwd,NaN,sedan,red,33.786500,-84.445400,2021-04-04T03:21:29-0600,Carvana is the safer way to buy a car During t...,wyoming,s60 t5 momentum sedan 4d
426877,NaN,34990,2020.0,cadillac,NaN,good,NaN,diesel,4174.0,clean,...,NaN,NaN,hatchback,white,33.779214,-84.411811,2021-04-04T03:21:17-0600,Carvana is the safer way to buy a car During t...,wyoming,xt4 sport suv 4d
426878,NaN,28990,2018.0,lexus,NaN,good,6 cylinders,gas,30112.0,clean,...,fwd,NaN,sedan,silver,33.786500,-84.445400,2021-04-04T03:21:11-0600,Carvana is the safer way to buy a car During t...,wyoming,es 350 sedan 4d
426879,NaN,30590,2019.0,bmw,NaN,good,NaN,gas,22716.0,clean,...,rwd,NaN,coupe,NaN,33.779214,-84.411811,2021-04-04T03:21:07-0600,Carvana is the safer way to buy a car During t...,wyoming,4 series 430i gran coupe