# Delete All Incomplete Entries

## <font color=MediumSlateBlue>1) Imports</font>

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
full_df = pd.read_csv(Path('./Resources/raw_data_combined_v2.csv'), index_col='uid')

C:\Users\fsurl\.conda\envs\SQL\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1,5,20,21,22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\fsurl\.conda\envs\SQL\lib\site-packages\numpy\lib\arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [3]:
print(f'Column Names:\n\n{full_df.columns.values}\n')
print(f'Column Types:\n\n{full_df.dtypes}\n')
print(f'Review Subset Data:\n\n{full_df}')

Column Names:

['city' 'price' 'year' 'manufacturer' 'make' 'condition' 'cylinders'
 'fuel' 'odometer' 'title_status' 'transmission' 'VIN' 'drive' 'size'
 'type' 'paint_color' 'lat' 'long' 'posting_date' 'desc' 'region' 'model']

Column Types:

city             object
price             int64
year            float64
manufacturer     object
make             object
condition        object
cylinders        object
fuel             object
odometer        float64
title_status     object
transmission     object
VIN              object
drive            object
size             object
type             object
paint_color      object
lat             float64
long            float64
posting_date     object
desc             object
region           object
model            object
dtype: object

Review Subset Data:

                 city  price    year   manufacturer            make  \
uid
6736984460  tricities   5000  1978.0           ford          bronco
6716121500  tricities   5000  2008.0          buick  lucerne cxl v6
6731405764  tricities  13500  2006.0            NaN        Pont GTO
6736958987  tricities   6200  2006.0  mercedes-benz             NaN
6736964819  tricities  37900  2016.0           ford            f350
...               ...    ...     ...            ...             ...
7301591192        NaN  23590  2019.0         nissan             NaN
7301591187        NaN  30590  2020.0          volvo             NaN
7301591147        NaN  34990  2020.0       cadillac             NaN
7301591140        NaN  28990  2018.0          lexus             NaN
7301591129        NaN  30590  2019.0            bmw             NaN

            condition    cylinders    fuel  odometer title_status  ... drive  \
uid                                                                ...
6736984460        NaN          NaN     gas       NaN        clean  ...   NaN
6716121500   like new  6 cylinders     gas   51000.0        clean  ...   fwd
6731405764  excellent  8 cylinders     gas   93000.0        clean  ...   rwd
6736958987        NaN          NaN     gas       NaN      rebuilt  ...   NaN
6736964819  excellent  8 cylinders  diesel   70500.0        clean  ...   4wd
...               ...          ...     ...       ...          ...  ...   ...
7301591192       good  6 cylinders     gas   32226.0        clean  ...   fwd
7301591187       good          NaN     gas   12029.0        clean  ...   fwd
7301591147       good          NaN  diesel    4174.0        clean  ...   NaN
7301591140       good  6 cylinders     gas   30112.0        clean  ...   fwd
7301591129       good          NaN     gas   22716.0        clean  ...   rwd

                 size       type paint_color        lat       long  \
uid
6736984460        NaN        NaN         NaN  37.132840 -95.785580
6716121500  full-size      sedan        grey  35.777999 -83.612533
6731405764   mid-size      coupe         red  36.333900 -82.340800
6736958987        NaN        NaN         NaN  36.000092 -84.018302
6736964819        NaN      truck       white  36.272932 -82.537537
...               ...        ...         ...        ...        ...
7301591192        NaN      sedan         NaN  33.786500 -84.445400
7301591187        NaN      sedan         red  33.786500 -84.445400
7301591147        NaN  hatchback       white  33.779214 -84.411811
7301591140        NaN      sedan      silver  33.786500 -84.445400
7301591129        NaN      coupe         NaN  33.779214 -84.411811

                        posting_date  \
uid
6736984460                2018-10-31
6716121500                2018-10-31
6731405764                2018-10-31
6736958987                2018-10-31
6736964819                2018-10-31
...                              ...
7301591192  2021-04-04T03:21:31-0600
7301591187  2021-04-04T03:21:29-0600
7301591147  2021-04-04T03:21:17-0600
7301591140  2021-04-04T03:21:11-0600
7301591129  2021-04-04T03:21:07-0600

                                                         desc   region  \
uid
6736984460                                                NaN      NaN
6716121500                                                NaN      NaN
6731405764                                                NaN      NaN
6736958987                                                NaN      NaN
6736964819                                                NaN      NaN
...                                                       ...      ...
7301591192  Carvana is the safer way to buy a car During t...  wyoming
7301591187  Carvana is the safer way to buy a car During t...  wyoming
7301591147  Carvana is the safer way to buy a car During t...  wyoming
7301591140  Carvana is the safer way to buy a car During t...  wyoming
7301591129  Carvana is the safer way to buy a car During t...  wyoming

                               model
uid
6736984460                       NaN
6716121500                       NaN
6731405764                       NaN
6736958987                       NaN
6736964819                       NaN
...                              ...
7301591192         maxima s sedan 4d
7301591187  s60 t5 momentum sedan 4d
7301591147          xt4 sport suv 4d
7301591140           es 350 sedan 4d
7301591129  4 series 430i gran coupe

[2537257 rows x 22 columns]

## <font color=MediumSlateBlue>2) Identify & Drop Null Entries</font>

### <font color=PaleGreen>2a) Count Number of Entries Before Dropping</font>

In [4]:
full_df.isnull().sum()

city             868276
price                 0
year               4371
manufacturer     148138
make             919997
condition       1078362
cylinders       1042756
fuel              21654
odometer         440035
title_status      26812
transmission      19557
VIN             1207068
drive            828098
size            1724116
type             761348
paint_color      866528
lat               21874
long              21874
posting_date         68
desc             677959
region          1668981
model           1679597
dtype: int64

### <font color=PaleGreen>2b) Drop Null Entries from the DataFrame</font>

In [5]:
# drop null entries:
# year/manufacturer/odometer(?)/lat/long/posting_date
full_df = full_df.dropna(subset=['posting_date', 'lat', 'long', 'manufacturer', 'year'])

### <font color=PaleGreen>2c) Verify removed entries</font>

In [6]:
full_df.isnull().sum()

city             819598
price                 0
year                  0
manufacturer          0
make             870615
condition       1002989
cylinders        966827
fuel              15861
odometer         382502
title_status      21713
transmission      14835
VIN             1090757
drive            751168
size            1613316
type             687176
paint_color      797093
lat                   0
long                  0
posting_date          0
desc             618521
region          1549709
model           1559954
dtype: int64

## <font color=MediumSlateBlue>3) Save Filtered DataFrame to a CSV</font>

### <font color=PaleGreen>3a) Save to a CSV</font>

In [7]:
full_df.to_csv(Path('./Resources/data_for_prez.csv'))

### <font color=PaleGreen>3b) Verify the CSV</font>

In [11]:
test_df = pd.read_csv(Path('./Resources/data_for_prez.csv'), index_col='uid')

C:\Users\fsurl\.conda\envs\SQL\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1,5,20,21,22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\fsurl\.conda\envs\SQL\lib\site-packages\numpy\lib\arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [12]:
test_df

,city,price,year,manufacturer,make,condition,cylinders,fuel,odometer,title_status,...,drive,size,type,paint_color,lat,long,posting_date,desc,region,model
uid,,,,,,,,,,,,,,,,,,,,,
6736984460,tricities,5000,1978.0,ford,bronco,NaN,NaN,gas,NaN,clean,...,NaN,NaN,NaN,NaN,37.132840,-95.785580,2018-10-31,NaN,NaN,NaN
6716121500,tricities,5000,2008.0,buick,lucerne cxl v6,like new,6 cylinders,gas,51000.0,clean,...,fwd,full-size,sedan,grey,35.777999,-83.612533,2018-10-31,NaN,NaN,NaN
6736958987,tricities,6200,2006.0,mercedes-benz,NaN,NaN,NaN,gas,NaN,rebuilt,...,NaN,NaN,NaN,NaN,36.000092,-84.018302,2018-10-31,NaN,NaN,NaN
6736964819,tricities,37900,2016.0,ford,f350,excellent,8 cylinders,diesel,70500.0,clean,...,4wd,NaN,truck,white,36.272932,-82.537537,2018-10-31,NaN,NaN,NaN
6727086483,tricities,1200,1992.0,mercedes-benz,benz,NaN,NaN,gas,194000.0,clean,...,NaN,NaN,NaN,NaN,36.416200,-83.010800,2018-10-31,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7301591192,NaN,23590,2019.0,nissan,NaN,good,6 cylinders,gas,32226.0,clean,...,fwd,NaN,sedan,NaN,33.786500,-84.445400,2021-04-04T03:21:31-0600,Carvana is the safer way to buy a car During t...,wyoming,maxima s sedan 4d
7301591187,NaN,30590,2020.0,volvo,NaN,good,NaN,gas,12029.0,clean,...,fwd,NaN,sedan,red,33.786500,-84.445400,2021-04-04T03:21:29-0600,Carvana is the safer way to buy a car During t...,wyoming,s60 t5 momentum sedan 4d
7301591147,NaN,34990,2020.0,cadillac,NaN,good,NaN,diesel,4174.0,clean,...,NaN,NaN,hatchback,white,33.779214,-84.411811,2021-04-04T03:21:17-0600,Carvana is the safer way to buy a car During t...,wyoming,xt4 sport suv 4d
7301591140,NaN,28990,2018.0,lexus,NaN,good,6 cylinders,gas,30112.0,clean,...,fwd,NaN,sedan,silver,33.786500,-84.445400,2021-04-04T03:21:11-0600,Carvana is the safer way to buy a car During t...,wyoming,es 350 sedan 4d
7301591129,NaN,30590,2019.0,bmw,NaN,good,NaN,gas,22716.0,clean,...,rwd,NaN,coupe,NaN,33.779214,-84.411811,2021-04-04T03:21:07-0600,Carvana is the safer way to buy a car During t...,wyoming,4 series 430i gran coupe