In [1]:
# Import Pandas library
import pandas as pd

# Import the Path module from the pathlib library
from pathlib import Path

# Import the matplotlib inline dependency
%matplotlib inline

import plotly.express as px
import os
from dotenv import load_dotenv

In [2]:
vehicles_used_pd = pd.read_csv(
    Path('../Resources/vehicles_mod.csv'),
    index_col="posting_date", 
    parse_dates=True, 
    infer_datetime_format=True
)
#Verify readability of raw file
vehicles_used_pd.head()

,id,region,price,year,manufacturer,model,condition,fuel,odometer,transmission,drive,size,type,paint_color,state,lat,long
posting_date,,,,,,,,,,,,,,,,,
2021-05-03 14:02:03-05:00,7316356412,auburn,15000,2013.0,ford,f-150 xlt,excellent,gas,128000.0,automatic,rwd,full-size,truck,black,al,32.592000,-85.51890
2021-04-29 17:19:18-05:00,7314560853,auburn,19900,2004.0,ford,f250 super duty,good,diesel,88000.0,automatic,4wd,full-size,pickup,blue,al,32.547500,-85.46820
2021-04-27 12:20:01-05:00,7313406529,auburn,14000,2012.0,honda,odyssey,excellent,gas,95000.0,automatic,fwd,full-size,mini-van,silver,al,32.628739,-85.46182
2021-04-26 11:15:36-05:00,7312847466,auburn,22500,2001.0,ford,f450,good,diesel,144700.0,manual,rwd,full-size,truck,white,al,32.630400,-85.40160
2021-04-24 18:39:59-05:00,7312144944,auburn,15000,2017.0,dodge,charger rt 4dr sedan,excellent,gas,90000.0,automatic,rwd,mid-size,sedan,grey,al,32.822400,-85.77040

In [3]:
vehicles_used_pd.tail()

,id,region,price,year,manufacturer,model,condition,fuel,odometer,transmission,drive,size,type,paint_color,state,lat,long
posting_date,,,,,,,,,,,,,,,,,
2021-04-06 21:04:03-06:00,7302963673,wyoming,18000,2005.0,chevrolet,silverado 1500 lt 4x4,excellent,gas,130000.0,automatic,4wd,full-size,truck,blue,wy,43.452800,-110.739300
2021-04-06 21:02:26-06:00,7302963273,wyoming,18000,1990.0,jeep,gand wagoneer,good,gas,114400.0,automatic,4wd,full-size,SUV,black,wy,43.452800,-110.739300
2021-04-05 18:10:52-06:00,7302384818,wyoming,9800,1985.0,nissan,300zx coupe with t-tops,like new,gas,115000.0,automatic,rwd,sub-compact,hatchback,red,wy,41.143700,-104.796200
2021-04-05 16:29:38-06:00,7302338378,wyoming,6800,1997.0,jaguar,xk8 convertible,good,gas,69550.0,automatic,rwd,compact,convertible,white,wy,43.642930,-108.222976
2021-04-05 15:18:42-06:00,7302301268,wyoming,0,2018.0,ram,2500,excellent,diesel,20492.0,automatic,4wd,full-size,truck,white,wy,45.082436,-94.334686

In [4]:
#Count the number of NaN values in the file
vehicles_used_pd.isnull().sum()

id              0
region          0
price           0
year            0
manufacturer    0
model           0
condition       0
fuel            0
odometer        0
transmission    0
drive           0
size            0
type            0
paint_color     0
state           0
lat             0
long            0
dtype: int64

In [6]:
# #Perform data clean-up 
# 
#STEP-1: Delete Blank Cells in the column for Posting Dates# 
#
# vehicles_used_pd.dropna(subset=["lat", "long", "condition"], inplace=True)

In [5]:
#Verify dataframe
vehicles_used_pd.head()

,id,region,price,year,manufacturer,model,condition,fuel,odometer,transmission,drive,size,type,paint_color,state,lat,long
posting_date,,,,,,,,,,,,,,,,,
2021-05-03 14:02:03-05:00,7316356412,auburn,15000,2013.0,ford,f-150 xlt,excellent,gas,128000.0,automatic,rwd,full-size,truck,black,al,32.592000,-85.51890
2021-04-29 17:19:18-05:00,7314560853,auburn,19900,2004.0,ford,f250 super duty,good,diesel,88000.0,automatic,4wd,full-size,pickup,blue,al,32.547500,-85.46820
2021-04-27 12:20:01-05:00,7313406529,auburn,14000,2012.0,honda,odyssey,excellent,gas,95000.0,automatic,fwd,full-size,mini-van,silver,al,32.628739,-85.46182
2021-04-26 11:15:36-05:00,7312847466,auburn,22500,2001.0,ford,f450,good,diesel,144700.0,manual,rwd,full-size,truck,white,al,32.630400,-85.40160
2021-04-24 18:39:59-05:00,7312144944,auburn,15000,2017.0,dodge,charger rt 4dr sedan,excellent,gas,90000.0,automatic,rwd,mid-size,sedan,grey,al,32.822400,-85.77040

In [8]:
vehicles_used_pd.isnull().sum()

id              0
region          0
price           0
year            0
manufacturer    0
model           0
condition       0
fuel            0
odometer        0
transmission    0
drive           0
size            0
type            0
paint_color     0
state           0
lat             0
long            0
dtype: int64

In [9]:
#Perform data clean-up 
#STEP-1: Delete Blank Cells in the column for Posting Dates# 
# vehicles_used_pd.dropna(subset=["size", "type", "paint_color"], inplace=True)

In [10]:
vehicles_used_pd.head()

,id,region,price,year,manufacturer,model,condition,fuel,odometer,transmission,drive,size,type,paint_color,state,lat,long
posting_date,,,,,,,,,,,,,,,,,
2021-05-03 14:02:03-05:00,7316356412,auburn,15000,2013.0,ford,f-150 xlt,excellent,gas,128000.0,automatic,rwd,full-size,truck,black,al,32.592000,-85.51890
2021-04-29 17:19:18-05:00,7314560853,auburn,19900,2004.0,ford,f250 super duty,good,diesel,88000.0,automatic,4wd,full-size,pickup,blue,al,32.547500,-85.46820
2021-04-27 12:20:01-05:00,7313406529,auburn,14000,2012.0,honda,odyssey,excellent,gas,95000.0,automatic,fwd,full-size,mini-van,silver,al,32.628739,-85.46182
2021-04-26 11:15:36-05:00,7312847466,auburn,22500,2001.0,ford,f450,good,diesel,144700.0,manual,rwd,full-size,truck,white,al,32.630400,-85.40160
2021-04-24 18:39:59-05:00,7312144944,auburn,15000,2017.0,dodge,charger rt 4dr sedan,excellent,gas,90000.0,automatic,rwd,mid-size,sedan,grey,al,32.822400,-85.77040

In [11]:
#Count the number of NaN values in the file
len(vehicles_used_pd)

80778

In [12]:
#Drop NaN final
# 
# vehicles_used_pd.dropna(inplace=True)

In [13]:
# Load the Mapbox API access token from the .env file
vehicles_used_pd

,id,region,price,year,manufacturer,model,condition,fuel,odometer,transmission,drive,size,type,paint_color,state,lat,long
posting_date,,,,,,,,,,,,,,,,,
2021-05-03 14:02:03-05:00,7316356412,auburn,15000,2013.0,ford,f-150 xlt,excellent,gas,128000.0,automatic,rwd,full-size,truck,black,al,32.592000,-85.518900
2021-04-29 17:19:18-05:00,7314560853,auburn,19900,2004.0,ford,f250 super duty,good,diesel,88000.0,automatic,4wd,full-size,pickup,blue,al,32.547500,-85.468200
2021-04-27 12:20:01-05:00,7313406529,auburn,14000,2012.0,honda,odyssey,excellent,gas,95000.0,automatic,fwd,full-size,mini-van,silver,al,32.628739,-85.461820
2021-04-26 11:15:36-05:00,7312847466,auburn,22500,2001.0,ford,f450,good,diesel,144700.0,manual,rwd,full-size,truck,white,al,32.630400,-85.401600
2021-04-24 18:39:59-05:00,7312144944,auburn,15000,2017.0,dodge,charger rt 4dr sedan,excellent,gas,90000.0,automatic,rwd,mid-size,sedan,grey,al,32.822400,-85.770400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-06 21:04:03-06:00,7302963673,wyoming,18000,2005.0,chevrolet,silverado 1500 lt 4x4,excellent,gas,130000.0,automatic,4wd,full-size,truck,blue,wy,43.452800,-110.739300
2021-04-06 21:02:26-06:00,7302963273,wyoming,18000,1990.0,jeep,gand wagoneer,good,gas,114400.0,automatic,4wd,full-size,SUV,black,wy,43.452800,-110.739300
2021-04-05 18:10:52-06:00,7302384818,wyoming,9800,1985.0,nissan,300zx coupe with t-tops,like new,gas,115000.0,automatic,rwd,sub-compact,hatchback,red,wy,41.143700,-104.796200
2021-04-05 16:29:38-06:00,7302338378,wyoming,6800,1997.0,jaguar,xk8 convertible,good,gas,69550.0,automatic,rwd,compact,convertible,white,wy,43.642930,-108.222976
2021-04-05 15:18:42-06:00,7302301268,wyoming,0,2018.0,ram,2500,excellent,diesel,20492.0,automatic,4wd,full-size,truck,white,wy,45.082436,-94.334686

In [ ]:
#User requirement-1 (Presentation)
# Add a conditional statement to the `vehicles_used_pd` DataFrame to filter vehicle list by region & price for a given odometer range 
# Test filter for vehicles when 75000<odometer<100000`. List Make, Region &  Price


# Print region, make &  price as a dataframe (Limit to top 10) & descending order

# multiple_filter_df = vehicles_used_pd.loc[
#     (vehicles_used_pd['odometer'] >=  75000) & (vehicles_used_pd['odometer'] < 100000) &
#     (vehicles_used_pd['price'] >= 15000) & (vehicles_used_pd['price'] < 30000) &
#     (vehicles_used_pd['region'] == 'houston') | (vehicles_used_pd['region'] == 'san diego')

# ]

In [11]:
mf_1 = vehicles_used_pd.loc[
    (vehicles_used_pd['region'] == 'houston') | (vehicles_used_pd['region'] == 'san diego')
]
mf_1

,id,region,price,year,manufacturer,model,condition,fuel,odometer,transmission,drive,size,type,paint_color,state,lat,long
posting_date,,,,,,,,,,,,,,,,,
2021-05-04 13:13:51-07:00,7316915159,san diego,4150,2008.0,kia,optima,good,gas,64100.0,automatic,fwd,mid-size,sedan,brown,ca,32.575300,-117.070700
2021-05-04 13:09:52-07:00,7316912835,san diego,6500,2013.0,ford,focus,excellent,gas,126000.0,automatic,fwd,compact,hatchback,silver,ca,32.811527,-116.940769
2021-05-04 13:05:50-07:00,7316910334,san diego,10890,2006.0,nissan,frontier,excellent,gas,88990.0,automatic,fwd,mid-size,truck,silver,ca,33.126912,-117.097615
2021-05-04 12:56:46-07:00,7316904741,san diego,11975,2003.0,harley-davidson,davidson,excellent,gas,207000.0,automatic,rwd,full-size,pickup,black,ca,34.070612,-117.383384
2021-05-04 12:48:49-07:00,7316900071,san diego,4200,2008.0,toyota,prius,good,hybrid,173000.0,automatic,fwd,compact,hatchback,custom,ca,32.799327,-117.234228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-29 15:34:08-04:00,7314473951,houston,4950,2008.0,mazda,cx7,excellent,gas,165000.0,automatic,fwd,mid-size,SUV,grey,tx,30.080501,-95.453053
2021-04-29 14:33:05-05:00,7314473405,houston,6950,2010.0,gmc,terrain sle,like new,gas,117000.0,automatic,fwd,full-size,SUV,custom,tx,30.081244,-95.452881
2021-04-29 14:32:21-05:00,7314472981,houston,5950,2007.0,nissan,armada se,good,gas,207000.0,automatic,rwd,full-size,SUV,blue,tx,30.080650,-95.453224
2021-04-29 14:22:37-05:00,7314467358,houston,9900,2007.0,dodge,grand caravan,excellent,gas,151800.0,automatic,fwd,mid-size,mini-van,blue,tx,29.682600,-95.122200
2021-04-29 14:22:33-05:00,7314467313,houston,29000,2006.0,ram,3500 mega cab,good,diesel,150300.0,automatic,4wd,full-size,truck,black,tx,30.211033,-95.647914

In [12]:
mf_2 = mf_1.loc[
    (mf_1['price'] >= 15000) & (mf_1['price'] < 30000)
]
mf_2

,id,region,price,year,manufacturer,model,condition,fuel,odometer,transmission,drive,size,type,paint_color,state,lat,long
posting_date,,,,,,,,,,,,,,,,,
2021-05-04 12:44:27-07:00,7316897561,san diego,18900,2017.0,chevrolet,malibu hybrid,excellent,hybrid,41500.0,automatic,fwd,mid-size,sedan,white,ca,33.191237,-117.273148
2021-05-04 12:01:53-07:00,7316872245,san diego,24500,2018.0,subaru,forester 2.5i premium,like new,gas,20760.0,automatic,4wd,mid-size,SUV,grey,ca,33.006700,-117.069000
2021-05-04 11:08:22-07:00,7316838931,san diego,22150,2018.0,toyota,prius prime,excellent,hybrid,31500.0,automatic,fwd,mid-size,hatchback,blue,ca,33.197800,-117.248200
2021-05-04 10:26:15-07:00,7316811546,san diego,24785,1985.0,toyota,land cruiser,excellent,diesel,72130.0,manual,4wd,mid-size,SUV,red,ca,32.747600,-117.163400
2021-05-04 10:08:41-07:00,7316799820,san diego,23995,2013.0,bmw,750li,like new,gas,95000.0,automatic,rwd,full-size,sedan,black,ca,32.778300,-117.133500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-29 18:25:46-05:00,7314590692,houston,15299,2010.0,rover,sport,good,gas,71600.0,automatic,4wd,full-size,SUV,black,tx,29.791400,-95.131700
2021-04-29 17:54:49-05:00,7314576993,houston,19300,2015.0,ford,transit 250,excellent,gas,220076.0,automatic,fwd,full-size,other,white,tx,29.689600,-95.510600
2021-04-29 17:15:19-04:00,7314529394,houston,27995,2015.0,chevrolet,tahoe lt,excellent,gas,91150.0,automatic,rwd,full-size,SUV,black,tx,29.827200,-95.426600
2021-04-29 16:14:47-05:00,7314529120,houston,23495,2013.0,mercedes-benz,benz gl550 4matic,excellent,gas,129727.0,automatic,4wd,full-size,SUV,white,tx,29.827200,-95.426600
2021-04-29 14:22:33-05:00,7314467313,houston,29000,2006.0,ram,3500 mega cab,good,diesel,150300.0,automatic,4wd,full-size,truck,black,tx,30.211033,-95.647914

In [13]:
mf_3 = mf_2.loc[
    (mf_2['odometer'] >= 75000) & (mf_2['odometer'] < 100000)
]
mf_3

,id,region,price,year,manufacturer,model,condition,fuel,odometer,transmission,drive,size,type,paint_color,state,lat,long
posting_date,,,,,,,,,,,,,,,,,
2021-05-04 10:08:41-07:00,7316799820,san diego,23995,2013.0,bmw,750li,like new,gas,95000.0,automatic,rwd,full-size,sedan,black,ca,32.778300,-117.133500
2021-05-03 20:04:30-07:00,7316577036,san diego,16000,2013.0,bmw,750i,good,gas,86000.0,automatic,rwd,full-size,sedan,white,ca,33.029300,-116.853500
2021-05-03 14:10:01-07:00,7316433164,san diego,21000,2011.0,porsche,cayenne s,good,gas,81925.0,automatic,4wd,full-size,SUV,grey,ca,32.891900,-117.203500
2021-05-03 09:35:11-07:00,7316260424,san diego,24999,2002.0,ford,f250 super cab xlt,excellent,diesel,98000.0,automatic,rwd,full-size,truck,white,ca,32.894064,-117.151031
2021-05-02 19:47:11-07:00,7316052761,san diego,29995,2018.0,jeep,wrangler jk,good,gas,83867.0,automatic,4wd,full-size,SUV,black,ca,33.946412,-117.295118
2021-05-02 19:45:17-07:00,7316052302,san diego,26495,2017.0,jeep,wrangler,good,gas,80449.0,automatic,4wd,full-size,SUV,black,ca,33.946412,-117.295118
2021-05-02 16:26:42-07:00,7315989179,san diego,15695,2015.0,infiniti,q50,excellent,gas,95136.0,automatic,rwd,full-size,sedan,blue,ca,33.006700,-117.069000
2021-05-01 16:04:00-07:00,7315558139,san diego,25000,2011.0,toyota,tundra,good,gas,77450.0,automatic,4wd,full-size,truck,white,ca,32.742500,-117.243300
2021-05-01 14:16:34-07:00,7315511584,san diego,21500,2004.0,bmw,e46 m3,excellent,gas,77800.0,manual,rwd,mid-size,convertible,grey,ca,32.965200,-117.121300
2021-05-01 13:39:19-07:00,7315492852,san diego,17800,2015.0,bmw,528i,excellent,gas,93200.0,automatic,rwd,full-size,sedan,grey,ca,33.229600,-117.336700
2021-04-30 22:10:02-07:00,7315184174,san diego,19900,2016.0,chevrolet,colorado,excellent,gas,77495.0,automatic,rwd,full-size,truck,red,ca,33.875577,-117.570384
2021-04-30 22:03:16-07:00,7315183090,san diego,23900,2018.0,ford,f-150,excellent,gas,75912.0,automatic,rwd,full-size,truck,black,ca,33.875577,-117.570384
2021-04-30 17:30:05-07:00,7315116386,san diego,18990,2007.0,chevrolet,corvette ls2,like new,gas,97000.0,automatic,rwd,full-size,coupe,black,ca,32.817800,-116.922300
2021-04-30 15:32:59-07:00,7315067866,san diego,15498,2014.0,bmw,320i,excellent,gas,78386.0,automatic,rwd,compact,sedan,black,ca,32.675500,-117.108069
2021-04-30 06:56:46-07:00,7314771669,san diego,16599,2011.0,bmw,750i,excellent,gas,80700.0,automatic,rwd,full-size,sedan,white,ca,32.637100,-117.067600
2021-05-04 12:13:39-04:00,7316764028,houston,20999,2013.0,toyota,tacoma,new,gas,82289.0,automatic,4wd,full-size,truck,grey,tx,29.745000,-95.732600
2021-05-03 23:16:07-05:00,7316592284,houston,28500,2017.0,ford,expedition,excellent,gas,80200.0,automatic,rwd,full-size,SUV,grey,tx,33.029900,-96.788900
2021-05-03 17:00:22-07:00,7316514732,houston,28850,2015.0,audi,s5,excellent,gas,76970.0,automatic,4wd,sub-compact,coupe,black,tx,29.747353,-95.643891
2021-05-03 16:07:30-07:00,7316491338,houston,19000,2015.0,lexus,rx 350,like new,gas,98000.0,automatic,fwd,mid-size,SUV,blue,tx,29.631107,-95.228205
2021-05-03 10:46:54-07:00,7316308078,houston,21999,2013.0,mercedes-benz,gl450 4matic,excellent,gas,86000.0,automatic,4wd,full-size,SUV,custom,tx,29.850564,-95.486972
2021-05-03 12:58:27-04:00,7316275930,houston,23900,2014.0,mercedes-benz,benz e350 4matic,excellent,gas,77245.0,automatic,fwd,mid-size,coupe,blue,tx,29.740979,-95.645428
2021-05-03 10:39:56-06:00,7316263517,houston,19999,2013.0,bmw,5-series 535i gt,excellent,gas,88000.0,automatic,4wd,full-size,SUV,custom,tx,29.850564,-95.486972
2021-05-03 11:23:23-05:00,7316252510,houston,15999,2012.0,mercedes-benz,benz glk350,excellent,gas,77000.0,automatic,rwd,full-size,SUV,black,tx,29.850564,-95.486972
2021-05-03 10:23:17-06:00,7316252435,houston,16999,2017.0,jeep,grand cherokee,like new,gas,89425.0,automatic,fwd,full-size,SUV,white,tx,29.720380,-95.535419
2021-05-02 16:25:48-05:00,7315939757,houston,21500,2006.0,ford,f450 super duty,good,diesel,93182.0,automatic,rwd,full-size,truck,white,tx,34.081200,-117.736200
2021-05-02 13:28:35-05:00,7315851643,houston,15000,2011.0,honda,pilot,excellent,gas,86000.0,automatic,fwd,full-size,SUV,grey,tx,29.596200,-95.458700
2021-05-01 22:44:13-05:00,7315637915,houston,28500,1985.0,cadillac,eldorado biarritz,excellent,gas,75692.0,automatic,fwd,full-size,convertible,white,tx,29.769600,-95.520100
2021-05-01 14:21:38-05:00,7315450784,houston,28900,2016.0,ram,2500 4x4,excellent,gas,97185.0,automatic,4wd,full-size,pickup,grey,tx,29.638213,-95.310709
2021-05-01 12:35:18-05:00,7315387751,houston,20999,2013.0,toyota,tacoma,new,gas,82289.0,automatic,4wd,full-size,truck,grey,tx,29.745000,-95.732600
2021-05-01 12:21:55-05:00,7315379505,houston,16999,2017.0,jeep,grand cherokee,like new,gas,89425.0,automatic,fwd,full-size,SUV,white,tx,29.720380,-95.535419
2021-04-30 10:50:42-05:00,7314835091,houston,19900,2015.0,chrysler,300c,like new,gas,82519.0,automatic,fwd,full-size,sedan,blue,tx,29.745749,-95.644741
2021-04-29 20:47:00-05:00,7314642567,houston,22000,2015.0,mercedes-benz,benz ml350 4matic,excellent,gas,83000.0,automatic,4wd,full-size,SUV,black,tx,29.571600,-95.099800
2021-04-29 19:30:23-05:00,7314617197,houston,22850,2013.0,dodge,durango,excellent,gas,80320.0,automatic,rwd,full-size,SUV,grey,tx,29.747353,-95.643891
2021-04-29 17:15:19-04:00,7314529394,houston,27995,2015.0,chevrolet,tahoe lt,excellent,gas,91150.0,automatic,rwd,full-size,SUV,black,tx,29.827200,-95.426600

In [110]:
mf_4 = mf_3.loc[mf_3['type'] == 'sedan']
mf_4 = mf_4.set_index(['region', 'condition', 'manufacturer'])
mf_4[['type', 'year', 'price', 'odometer', 'paint_color', 'id']]

                                   type    year  price  odometer paint_color  \
region    condition manufacturer
san diego like new  bmw           sedan  2013.0  23995   95000.0       black
          good      bmw           sedan  2013.0  16000   86000.0       white
          excellent infiniti      sedan  2015.0  15695   95136.0        blue
                    bmw           sedan  2015.0  17800   93200.0        grey
                    bmw           sedan  2014.0  15498   78386.0       black
                    bmw           sedan  2011.0  16599   80700.0       white
houston   like new  chrysler      sedan  2015.0  19900   82519.0        blue

                                          id
region    condition manufacturer
san diego like new  bmw           7316799820
          good      bmw           7316577036
          excellent infiniti      7315989179
                    bmw           7315492852
                    bmw           7315067866
                    bmw           7314771669
houston   like new  chrysler      7314835091

# What We Want

1. [Above Example]
    - Region (Any 2 regions) 
    - price (low_price <= x < high_price) 
    - odometer (low_mileage <= x < high_mileage) 
    - type
    - set the index
2. [For Presentation #1]
    - Region: any 2 regions
    - **Odometer**: in a certain range
    - Condition: specific condition
    - Type: specific vehicle type 
3. [For Presentation #2]
    - Region: any 2 regions
    - **Price**: in a certain range
    - Condition: specific condition
    - Type: specific vehicle type 





Show the above table with a plot

In [125]:
print(f'Columns: {vehicles_used_pd.columns.values}')
print_list = list(vehicles_used_pd['region'].unique())
print(f'Values:\n{print_list}')

Columns: ['id' 'region' 'price' 'year' 'manufacturer' 'model' 'condition' 'fuel'
 'odometer' 'transmission' 'drive' 'size' 'type' 'paint_color' 'state'
 'lat' 'long']
Values:
['auburn', 'birmingham', 'dothan', 'florence / muscle shoals', 'gadsden-anniston', 'huntsville / decatur', 'mobile', 'montgomery', 'tuscaloosa', 'anchorage / mat-su', 'fairbanks', 'kenai peninsula', 'southeast alaska', 'flagstaff / sedona', 'mohave county', 'phoenix', 'prescott', 'show low', 'sierra vista', 'tucson', 'yuma', 'fayetteville', 'fort smith', 'jonesboro', 'little rock', 'texarkana', 'bakersfield', 'chico', 'fresno / madera', 'gold country', 'hanford-corcoran', 'humboldt county', 'imperial county', 'inland empire', 'los angeles', 'mendocino county', 'merced', 'modesto', 'monterey bay', 'orange county', 'palm springs', 'redding', 'reno / tahoe', 'sacramento', 'san diego', 'san luis obispo', 'santa barbara', 'santa maria', 'SF bay area', 'siskiyou county', 'stockton', 'susanville', 'ventura county', 'visalia-tulare', 'yuba-sutter', 'boulder', 'colorado springs', 'denver', 'eastern CO', 'fort collins / north CO', 'high rockies', 'pueblo', 'western slope', 'eastern CT', 'hartford', 'new haven', 'northwest CT', 'washington, DC', 'delaware', 'daytona beach', 'florida keys', 'ft myers / SW florida', 'gainesville', 'heartland florida', 'jacksonville', 'lakeland', 'north central FL', 'ocala', 'okaloosa / walton', 'orlando', 'panama city', 'pensacola', 'sarasota-bradenton', 'south florida', 'space coast', 'st augustine', 'tallahassee', 'tampa bay area', 'treasure coast', 'albany', 'athens', 'atlanta', 'augusta', 'brunswick', 'columbus', 'macon / warner robins', 'northwest GA', 'savannah / hinesville', 'statesboro', 'valdosta', 'hawaii', 'boise', 'east idaho', 'lewiston / clarkston', 'pullman / moscow', "spokane / coeur d'alene", 'twin falls', 'bloomington-normal', 'champaign urbana', 'chicago', 'decatur', 'la salle co', 'mattoon-charleston', 'peoria', 'quad cities, IA/IL', 'rockford', 'southern illinois', 'springfield', 'st louis, MO', 'western IL', 'bloomington', 'evansville', 'fort wayne', 'indianapolis', 'kokomo', 'lafayette / west lafayette', 'muncie / anderson', 'richmond', 'south bend / michiana', 'terre haute', 'ames', 'cedar rapids', 'des moines', 'dubuque', 'fort dodge', 'iowa city', 'mason city', 'omaha / council bluffs', 'sioux city', 'southeast IA', 'waterloo / cedar falls', 'kansas city, MO', 'lawrence', 'manhattan', 'northwest KS', 'salina', 'southeast KS', 'southwest KS', 'topeka', 'wichita', 'bowling green', 'eastern kentucky', 'huntington-ashland', 'lexington', 'louisville', 'owensboro', 'western KY', 'baton rouge', 'central louisiana', 'houma', 'lafayette', 'lake charles', 'monroe', 'new orleans', 'shreveport', 'maine', 'annapolis', 'baltimore', 'cumberland valley', 'eastern shore', 'frederick', 'southern maryland', 'western maryland', 'boston', 'cape cod / islands', 'south coast', 'western massachusetts', 'worcester / central MA', 'ann arbor', 'battle creek', 'central michigan', 'detroit metro', 'flint', 'grand rapids', 'holland', 'jackson', 'kalamazoo', 'lansing', 'muskegon', 'northern michigan', 'port huron', 'saginaw-midland-baycity', 'southwest michigan', 'the thumb', 'upper peninsula', 'bemidji', 'brainerd', 'duluth / superior', 'fargo / moorhead', 'mankato', 'minneapolis / st paul', 'rochester', 'southwest MN', 'st cloud', 'gulfport / biloxi', 'hattiesburg', 'meridian', 'north mississippi', 'southwest MS', 'columbia / jeff city', 'joplin', 'kirksville', 'lake of the ozarks', 'southeast missouri', 'st joseph', 'st louis', 'billings', 'bozeman', 'butte', 'eastern montana', 'great falls', 'helena', 'kalispell', 'missoula', 'asheville', 'boone', 'charlotte', 'eastern NC', 'greensboro', 'hickory / lenoir', 'outer banks', 'raleigh / durham / CH', 'wilmington', 'winston-salem', 'grand island', 'lincoln', 'north platte', 'scottsbluff / panhandle', 'elko', 'las vegas', 'central NJ', 'jersey shore', 'north jersey', 'south jersey', 'albuquerque', 'clovis / portales', 'farmington', 'las cruces', 'roswell / carlsbad', 'santa fe / taos', 'binghamton', 'buffalo', 'catskills', 'chautauqua', 'elmira-corning', 'finger lakes', 'glens falls', 'hudson valley', 'ithaca', 'long island', 'new york city', 'oneonta', 'plattsburgh-adirondacks', 'potsdam-canton-massena', 'syracuse', 'twin tiers NY/PA', 'utica-rome-oneida', 'watertown', 'new hampshire', 'bismarck', 'grand forks', 'north dakota', 'akron / canton', 'ashtabula', 'chillicothe', 'cincinnati', 'cleveland', 'dayton / springfield', 'lima / findlay', 'mansfield', 'northern panhandle', 'parkersburg-marietta', 'sandusky', 'toledo', 'tuscarawas co', 'youngstown', 'zanesville / cambridge', 'fort smith, AR', 'lawton', 'northwest OK', 'oklahoma city', 'stillwater', 'texoma', 'tulsa', 'bend', 'corvallis/albany', 'east oregon', 'eugene', 'klamath falls', 'medford-ashland', 'oregon coast', 'portland', 'roseburg', 'salem', 'altoona-johnstown', 'erie', 'harrisburg', 'lancaster', 'lehigh valley', 'meadville', 'philadelphia', 'pittsburgh', 'poconos', 'reading', 'scranton / wilkes-barre', 'state college', 'williamsport', 'york', 'rhode island', 'charleston', 'columbia', 'florence', 'greenville / upstate', 'hilton head', 'myrtle beach', 'northeast SD', 'pierre / central SD', 'rapid city / west SD', 'sioux falls / SE SD', 'south dakota', 'chattanooga', 'clarksville', 'cookeville', 'knoxville', 'memphis', 'nashville', 'tri-cities', 'abilene', 'amarillo', 'austin', 'beaumont / port arthur', 'brownsville', 'college station', 'corpus christi', 'dallas / fort worth', 'deep east texas', 'del rio / eagle pass', 'el paso', 'galveston', 'houston', 'killeen / temple / ft hood', 'laredo', 'lubbock', 'mcallen / edinburg', 'odessa / midland', 'san angelo', 'san antonio', 'san marcos', 'southwest TX', 'tyler / east TX', 'victoria', 'waco', 'wichita falls', 'logan', 'ogden-clearfield', 'provo / orem', 'salt lake city', 'st george', 'vermont', 'charlottesville', 'danville', 'fredericksburg', 'harrisonburg', 'lynchburg', 'new river valley', 'norfolk / hampton roads', 'roanoke', 'southwest VA', 'winchester', 'bellingham', 'kennewick-pasco-richland', 'moses lake', 'olympic peninsula', 'seattle-tacoma', 'skagit / island / SJI', 'wenatchee', 'yakima', 'eastern panhandle', 'morgantown', 'southern WV', 'west virginia (old)', 'appleton-oshkosh-FDL', 'eau claire', 'green bay', 'janesville', 'kenosha-racine', 'la crosse', 'madison', 'milwaukee', 'northern WI', 'sheboygan', 'wausau', 'wyoming']

# <FONT COLOR=cyan>DRAFT START:

In [114]:
region_1 = 'houston'
region_2 = 'san diego'
odo_low = 75000
odo_high = 100000
index = ['region', 'condition', 'manufacturer']
return_columns = ['type', 'year', 'price', 'odometer', 'paint_color', 'id']

a1_df = vehicles_used_pd.loc[
    (vehicles_used_pd['region'] == region_1) | 
    (vehicles_used_pd['region'] == region_2)
]
a2_df = a1_df.loc[
    (a1_df['odometer'] >= odo_low) & 
    (a1_df['odometer'] < odo_high)
]
a2_df = a2_df.set_index(index)
a2_df[return_columns]

                                     type    year  price  odometer  \
region    condition manufacturer
san diego excellent nissan          truck  2006.0  10890   88990.0
          good      ford            truck  1964.0  10000   75268.0
                    kia             sedan  2015.0  11000   98000.0
          like new  bmw             sedan  2013.0  23995   95000.0
          good      lexus           sedan  2004.0   8900   88700.0
...                                   ...     ...    ...       ...
houston   excellent toyota          sedan  2012.0   9750   99165.0
                    mercedes-benz     SUV  2012.0  14995   91622.0
                    infiniti        coupe  2007.0   8995   88521.0
                    ford           pickup  2006.0   4999   77426.0
                    gmc             truck  2015.0  35000   82000.0

                                  paint_color          id
region    condition manufacturer
san diego excellent nissan             silver  7316910334
          good      ford                green  7316849899
                    kia                  blue  7316844084
          like new  bmw                 black  7316799820
          good      lexus              silver  7316781620
...                                       ...         ...
houston   excellent toyota              black  7314528265
                    mercedes-benz       black  7314527174
                    infiniti             grey  7314524872
                    ford                white  7314490476
                    gmc                silver  7314484857

[172 rows x 6 columns]